package br.com.harmony.domain.validation;

public enum ValidationErrorCode {
    REQUIRED_FIELD, EMPTY_SEQUENCE, SEQUENCE_LENGTH_MISMATCH, PHRASE_TOO_LONG,
    INVALID_KEY_FORMAT, UNSUPPORTED_KEY, INVALID_CHORD_FORMAT, UNSUPPORTED_CHORD,
    INVALID_PITCH_FORMAT, UNSUPPORTED_PITCH, SOPRANO_OUT_OF_RANGE
}
